system:
  mode: forward-test
  startup_time: 09:30
  checkpoint_interval_seconds: 300
  latency_thresholds:
    features: 12.0
    ml: 20.0
    risk: 8.0
  latency_violation_limit: 3
session:
  enabled: true
  start_time: 09:45
  end_time: '23:50'
  pre_open_minutes: 10
  post_close_minutes: 5
  allowed_weekdays:
  - 0
  - 1
  - 2
  - 3
  - 4
environment: development
logging:
  level: DEBUG
datafeed:
  sandbox_token: t.FVti568rNsdMJIuNMApjAMfCNJy8mfZaOgJmb03gpcO1ahFDM-_ttXCX4dfHYmketl9JsmDahGQ7mzSfrrhb6Q
  use_sandbox: false
  allow_tokenless: true
  instruments:
  - BBG004730N88
  - BBG004731032
  - BBG004730RP0
  - BBG0047315D0
  - BBG004731371
  - BBG004731354
  - BBG004731489
  - BBG004730ZJ9
  - BBG004S68507
  - BBG004S680K0
  - BBG004S68157
  - BBG004S686W0
  - BBG004S683W7
  - BBG004S683X6
  - BBG004S68696
  - BBG004S686K0
  - BBG00QPYJ5H0
  - BBG00QPYJ639
  - BBG006L8G4H1
  - BBG00F3NC364
  monitored_instruments:
  - FUTSI1224000
  - FUTRI1224000
  - FUTBR1224000
  - FUTGAZP1224000
  - FUTSBRF1224000
  - FUTLKOH1224000
  - FUTGMKN1224000
  - FUTROSN1224000
  - FUTNVTK1224000
  - FUTPLZL1224000
  max_active_instruments: 15
  monitor_pool_size: 30
  trade_history_size: 200
  candle_history_size: 240
  instrument_classes:
    BBG004730N88: equity
    BBG004731032: equity
    BBG004730RP0: equity
    BBG0047315D0: equity
    BBG004731371: equity
    BBG004731354: equity
    BBG004731489: equity
    BBG004730ZJ9: equity
    BBG004S68507: equity
    BBG004S680K0: equity
    BBG004S68157: equity
    BBG004S686W0: equity
    BBG004S683W7: equity
    BBG004S683X6: equity
    BBG004S68696: equity
    BBG004S686K0: equity
    BBG00QPYJ5H0: equity
    BBG00QPYJ639: equity
    BBG006L8G4H1: equity
    BBG00F3NC364: equity
    FUTSI1224000: futures
    FUTRI1224000: futures
    FUTBR1224000: futures
    FUTGAZP1224000: futures
    FUTSBRF1224000: futures
    FUTLKOH1224000: futures
    FUTGMKN1224000: futures
    FUTROSN1224000: futures
    FUTNVTK1224000: futures
    FUTPLZL1224000: futures
  depth: 10
  current_cache_ttl: 60
  current_cache_size: 50
  history_length: 30
  soft_rss_limit_mb: 400
  hard_rss_limit_mb: 700
  reconnect_delay: 1.0
  production_token: t.baeBGxS1nYnaHLZ7tC328DzwPNpTQwDq70GZ8YSp3Q1Ek0N4g2Htzv3hBzbQIrsdcu70xICbCgDIq_19SWEppA
features:
  lob_levels: 10
  rolling_window: 20
ml:
  batch_size: 64
  model_dir: ./runtime/models
  weights:
    lstm_ob: 0.35
    gbdt_features: 0.25
    transformer_temporal: 0.25
    svm_volatility: 0.15
  class_weights:
    equity:
      lstm_ob: 0.35
      gbdt_features: 0.25
      transformer_temporal: 0.25
      svm_volatility: 0.15
    futures:
      lstm_ob: 0.3
      gbdt_features: 0.3
      transformer_temporal: 0.25
      svm_volatility: 0.15
risk:
  max_position: 50
  max_daily_loss: 10000.0
  max_order_rate_per_minute: 120
  max_gross_exposure: 500000.0
  max_consecutive_losses: 3
  loss_cooldown_minutes: 15
  capital_base: 500000.0
  max_risk_per_instrument: 0.05
  daily_loss_limit_pct: 0.02
  max_exposure_pct: 0.5
  vix_threshold: 0.4
risk_schedule:
  rotation_interval_seconds: 60
  position_check_interval_seconds: 10
  drift_check_interval_seconds: 1800
  hedging_interval_seconds: 300
execution:
  account_id: ''
storage:
  base_path: ./runtime
  signals_db: ./runtime/signals.db
  health_db: ./runtime/health_check.db
  orderbooks_path: ./runtime/orderbooks.db
  trades_path: ./runtime/trades
  candles_path: ./runtime/candles
  features_path: ./runtime/features
  parquet_compression: snappy
  enable_zstd: true
  cache_flush_min_seconds: 1.0
  cache_flush_max_seconds: 5.0
  cache_target_buffer: 50
bus:
  enabled: true
  host: 127.0.0.1
  port: 8787
dashboard:
  auto_start: true
  host: 127.0.0.1
  port: 5000
  repository_path: ./runtime/signals.db
  refresh_interval_ms: 1000
  signal_limit: 25
  title: Scalp System Control Room
  headless: false
disaster_recovery:
  enabled: true
  replication_path: ./runtime/backups
  include_patterns:
  - '*.db'
  - '*.json'
  - '*.jsonl'
  interval_minutes: 30
  max_snapshots: 12
monitoring:
  cpu_soft_limit: 90.0
  memory_soft_limit: 85.0
  gpu_soft_limit: 90.0
  audit_log_filename: audit.log
  heartbeat_enabled: true
  heartbeat_interval_seconds: 5.0
  heartbeat_miss_threshold: 3
security:
  encryption_key_path: ./runtime/secret.key
notifications:
  telegram_bot_token: ''
  telegram_chat_id: ''
  enable_sound_alerts: false
  liquidity_spread_threshold_bps: 5.0
  cooldown_seconds: 30
fallback:
  enabled: true
  max_signals_per_hour: 10
  imbalance_threshold: 0.7
  volatility_threshold: 0.01
  confidence: 0.7
connectivity:
  primary_label: fiber
  backup_label: lte
  failure_threshold: 1
  recovery_message_count: 2
  failover_latency_ms: 150
manual_override:
  enabled: false
  flag_path: ./runtime/manual_override.flag
  poll_interval_seconds: 1.0
  auto_resume_minutes: null
reporting:
  enabled: true
  interval_minutes: 60
  max_history_days: 14
  report_path: ./runtime/reports/performance.jsonl
training:
  dataset_path: ./data/training.jsonl
  output_dir: ./models
  epochs: 5
  learning_rate: 0.01
  validation_split: 0.2
  min_samples: 10
  enable_quantization: true
  quantization_int8_threshold: 0.5
training_schedule:
  enabled: true
  daily_time: '18:45'
  weekdays:
  - 0
  - 1
  - 2
  - 3
  - 4
  require_forward_window: true
backtest:
  dataset_path: ./data/backtest.jsonl
  initial_capital: 250000.0
  transaction_cost_bps: 0.8
  slippage_bps: 0.5
  max_orders: 500
brokers:
  tinkoff:
    tokens_file: ./runtime/tinkoff_tokens.json
